[package]
name = "usid"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"], optional = true }
uuid = { version = "1.17.0", features = ["serde", "v4"] }

[features]
serde = ["dep:serde"]
